name: pr-check

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pr-check:
    strategy:
      matrix:
        python-version: ["3.6", "3.7"]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install tox
      run: python -m pip install --upgrade pip tox tox-gh-actions virtualenv setuptools
    - name: run tox
      run: tox
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
